version: "3.8"

services:
   backend:
      build:
         context: ./server/movie-database
         dockerfile: Dockerfile
      volumes:
         - ./server:/app
      ports:
         - "3000:3000"
      environment:
         - NODE_ENV=development

   frontend:
      build:
         context: ./front/movie-searcher
         dockerfile: Dockerfile
      volumes:
         - ./app/certificates-app:/app
      ports:
         - "5000:5000"
      environment:
         - NODE_ENV=development
      depends_on:
         - backend
