import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Providers } from "./store/Provider";

const roboto = Roboto({
   weight: ["300", "400", "500", "700"],
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang='en'>
         <body className={roboto.className}>
            <Providers>{children}</Providers>
         </body>
      </html>
   );
}

export default RootLayout;
